CREATE TABLE IF NOT EXISTS category (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(25)
);

Insert into category(title) values ('KIEMHIEP');
Insert into category(title) values ('NGONTINH');
Insert into category(title) values ('DOTHI');
Insert into category(title) values ('QUANTRUONG');
Insert into category(title) values ('VONGDU');
Insert into category(title) values ('KHOAHUYEN');
Insert into category(title) values ('HUYENHUYEN');
Insert into category(title) values ('DIGIOI');
Insert into category(title) values ('DINANG');
Insert into category(title) values ('QUANSU');
Insert into category(title) values ('LICHSU');
Insert into category(title) values ('XUYENKHONG');
Insert into category(title) values ('TRONGSINH');
Insert into category(title) values ('TRINHTHAM');
Insert into category(title) values ('THAMHIEM');
Insert into category(title) values ('LINHDI');
Insert into category(title) values ('TRUYENSAC');
Insert into category(title) values ('TRUYENNGUOC');
Insert into category(title) values ('TRUYENSUNG');
Insert into category(title) values ('TRUYENCUNGDAU');
Insert into category(title) values ('TRUYENNUCUONG');
Insert into category(title) values ('TRUYENGIADAU');
Insert into category(title) values ('DONGPHUONG');
Insert into category(title) values ('DAMMY');
Insert into category(title) values ('BACHHOP');
Insert into category(title) values ('HAIHUOC');
Insert into category(title) values ('DIENVAN');
Insert into category(title) values ('CODAI');
Insert into category(title) values ('MATTHE');
Insert into category(title) values ('TRUYENTEEN');
Insert into category(title) values ('PHUONGTAY');
Insert into category(title) values ('NUPHU');
Insert into category(title) values ('LIGHTNOVEL');
Insert into category(title) values ('VIETNAM');
Insert into category(title) values ('DOANVAN');
Insert into category(title) values ('TRUYENKHAC');

